name: Deploy to EC2

on:
  push:
    branches:
      - main
env:
  AWS_DEFAULT_REGION: ap-northeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }} # 인스턴스 IP
          username: ubuntu # 우분투 아이디
          key: ${{ secrets.EC2_KEY }} # ec2 instance pem key
          port: 22 # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/pcg
            git pull -f origin main
            bun i
            bun run typeorm:migrate:run
            bun run build
