name: Deploy to EC2

on:
  push:
    branches:
      - main
env:
  AWS_DEFAULT_REGION: ap-northeast-2
  SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
  EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}
  npm: /home/ubuntu/.nvm/versions/node/v20.12.0/bin/npm
  bun: /home/ubuntu/.nvm/versions/node/v20.12.0/bin/bun

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
        with:
          host: $EC2_IP # 인스턴스 IP
          username: ubuntu # 우분투 아이디
          key: $SSH_PRIVATE_KEY # ec2 instance pem key
          port: 22 # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/pcg
            git pull -f origin main
            bun i
            bun run typeorm:migrate:run
            bun run build
